version: '3'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trainer
    volumes:
      - 'postgres_data:/var/lib/postgresql'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 5s
      retries: 10

  dbmate:
    image: amacneil/dbmate:2.10.0
    container_name: dbmate
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/trainer?sslmode=disable
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: -d "/app/db/migrations" up

volumes:
  postgres_data:
